services:
  builder:
    build:
      context: .
      dockerfile: dockerfile
    image: ecotrip_builder_image
    container_name: ecotrip_builder

    dns:
      - 8.8.8.8
      - 1.1.1.1

    working_dir: /app

    volumes:
      - .:/app
      - gradle_cache:/root/.gradle

    env_file:
      - .env

    environment:
      EXPO_TOKEN: ${EXPO_TOKEN}
      EXPO_PUBLIC_GOOGLE_MAPS_APIKEY: ${EXPO_PUBLIC_GOOGLE_MAPS_APIKEY}
      EXPO_PUBLIC_API_URL: ${EXPO_PUBLIC_API_URL}

    command: >
      bash -c "
      yarn install --frozen-lockfile &&
      eas build --platform android --local --profile development
      "
    tty: true
    stdin_open: true

volumes:
  gradle_cache:
